version: '3.9'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - common
    depends_on:
      - node14
      - node16
  node14:
    build:
      context: .
      dockerfile: Node14.Dockerfile
    networks:
      - common
  node16:
    build:
      context: .
      dockerfile: Node16.Dockerfile
    networks:
      - common
networks:
  common: